baseurl = "https://example.com"
title = "Fossil-VR"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
sitename = "Chatham Fossil VR Project"
faviconfile = "images/favicon.png"
highlightjs = true
highlightjslanguages = ["r", "python", "stan"]
uselatex = true
progressively = false
# commentsrepo = "user/repo"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[[menu.primary]]
name = "About"
url = "/"
weight = 1
[[menu.primary]]
name = "VR Project"
url = "/VR Project/"
weight = 2
[[menu.primary]]
name = "Model Downloads"
url = "/downloads"
weight = 3
